### ISSUE TITLE
PECO AJUDA

### ISSUE THREAD

**Issue by SIbava** [hxphp/docs#22]
Fatal error: Uncaught Exception: Erro fatal: A view <'C:\wamp64\www\sistema\app\views\error404\index.phtml'> não foi encontrada. Por favor, crie a view e tente novamente. in C:\wamp64\www\sistema\vendor\hxphp\framework\src\HXPHP\System\View\Core.php:303 Stack trace: #0 C:\wamp64\www\sistema\vendor\hxphp\framework\src\HXPHP\System\App.php(120): HXPHP\System\View\Core->flush() #1 C:\wamp64\www\sistema\index.php(40): HXPHP\System\App->run() #2 {main} thrown in C:\wamp64\www\sistema\vendor\hxphp\framework\src\HXPHP\System\View\Core.php on line 303

**Comment by celsonguila** [comment]
Saudações
Não sei se cheguei tarde para ajuda-lo. verifique o seguinte:

Verifique se não apagou esta pasta :
Dentro da pasta app/views/ deve conter uma pasta com o nome error404 e dentro dela o ficheiro index.phtml;
